import React from 'react'
import { Card, Empty, FormActions, Modal, PageHeader } from '../components/UI.jsx'
import { downloadCsv, money, monthLabel, uid } from '../utils.js'

export default function Financials({ data, period, setFinancials }) {
  const [open, setOpen] = React.useState(false)
  const rows = data.financials.filter((row) => row.period === period)
  const sales = rows.filter((row) => row.type === 'Venta').reduce((sum, row) => sum + row.amount, 0)
  const expenses = rows.filter((row) => row.type === 'Gasto').reduce((sum, row) => sum + row.amount, 0)
  const rents = data.rents.filter((row) => row.period === period).reduce((sum, row) => sum + row.amount, 0)
  const save = (event) => { event.preventDefault(); const form = new FormData(event.currentTarget); const unit = data.units.find((row) => row.id === form.get('unitId')); setFinancials([...data.financials, { id: uid(), period, unitId: unit.id, unitName: unit.name, code: unit.code, type: form.get('type'), concept: form.get('concept'), date: form.get('date'), amount: Number(form.get('amount')) }]); setOpen(false) }
  const unitRows = data.units.map((unit) => { const values = rows.filter((row) => row.unitId === unit.id); const unitSales = values.filter((row) => row.type === 'Venta').reduce((s, r) => s + r.amount, 0); const unitExpenses = values.filter((row) => row.type === 'Gasto').reduce((s, r) => s + r.amount, 0); const unitRents = data.rents.filter((row) => row.period === period && row.unitId === unit.id).reduce((s, r) => s + r.amount, 0); return { ...unit, sales: unitSales, expenses: unitExpenses, rents: unitRents, result: unitSales - unitExpenses - unitRents } })
  return <>
    <PageHeader eyebrow="CENTRO FINANCIERO MENSUAL" title={`Estado financiero · ${monthLabel(period)}`} description="Todas las sucursales y sus registros alimentan el análisis automáticamente." actions={<><button className="secondary" onClick={() => downloadCsv(`estado-${period}.csv`, unitRows)}>▦ Excel/CSV</button><button onClick={() => setOpen(true)}>＋ Venta o gasto</button></>} />
    <div className="summary-strip"><div><small>Ventas consolidadas</small><b>{money(sales)}</b></div><div><small>Todos los gastos</small><b>− {money(expenses + rents)}</b></div><div><small>Rentas</small><b>− {money(rents)}</b></div><div><small>Utilidad neta</small><b>{money(sales - expenses - rents)}</b></div></div>
    <Card title="Estado por sucursal" subtitle="Cada alta aparece como una unidad contable independiente"><table><thead><tr><th>Sucursal</th><th>Ventas</th><th>Gastos</th><th>Rentas</th><th>Utilidad neta</th></tr></thead><tbody>{unitRows.map((row) => <tr key={row.id}><td>{row.code}<small>{row.name}</small></td><td>{money(row.sales)}</td><td>− {money(row.expenses)}</td><td>− {money(row.rents)}</td><td className={row.result < 0 ? 'negative' : 'positive'}>{money(row.result)}</td></tr>)}</tbody></table></Card>
    <Card title="Todos los movimientos integrados" subtitle={`${rows.length} registros`}>{rows.length ? <table><thead><tr><th>Fecha</th><th>Sucursal</th><th>Tipo</th><th>Concepto</th><th>Monto</th></tr></thead><tbody>{rows.map((row) => <tr key={row.id}><td>{row.date}</td><td>{row.code}</td><td>{row.type}</td><td>{row.concept}</td><td>{money(row.amount)}</td></tr>)}</tbody></table> : <Empty>Las sucursales ya forman parte del análisis; aún no hay movimientos para este periodo.</Empty>}</Card>
    {open && <Modal title="Registrar venta o gasto" onClose={() => setOpen(false)}><form onSubmit={save}><label>Sucursal<select name="unitId">{data.units.map((row) => <option key={row.id} value={row.id}>{row.code} · {row.name}</option>)}</select></label><div className="form-row"><label>Tipo<select name="type"><option>Venta</option><option>Gasto</option></select></label><label>Fecha<input type="date" name="date" required /></label></div><label>Concepto<input name="concept" required /></label><label>Monto<input type="number" name="amount" min="0" required /></label><FormActions onCancel={() => setOpen(false)} submitLabel="Guardar movimiento" /></form></Modal>}
  </>
}
