import type {
  Appointment,
  BillingCard,
  BillingHistoryEntry,
  BillingLocation,
  BillingProfile,
  BranchInventory,
  Client,
  ClientSourceOption,
  CashExpense,
  EmployeeRole,
  ExpenseType,
  InventoryMovement,
  InventoryMovementReason,
  MasterUser,
  PaymentMethodOption,
  Product,
  ReceiptSettings,
  RequiredClientFields,
  RetailDeal,
  SalesCompetition,
  Seller,
  LayawayRecord,
  Ticket,
} from "./types";

const createCurrentBusinessDayTimestamp = (time: string) => {
  const date = new Intl.DateTimeFormat("en-CA", {
    timeZone: "America/Mexico_City",
    year: "numeric",
    month: "2-digit",
    day: "2-digit",
  }).format(new Date());
  const createdAtIso = `${date}T${time}:00-06:00`;
  return {
    createdAtIso,
    createdAt: new Intl.DateTimeFormat("es-MX", {
      day: "2-digit",
      month: "short",
      year: "numeric",
      hour: "2-digit",
      minute: "2-digit",
      timeZone: "America/Mexico_City",
    })
      .format(new Date(createdAtIso))
      .replace(",", " ·"),
  };
};

const mockToday0915 = createCurrentBusinessDayTimestamp("09:15");
const mockToday1018 = createCurrentBusinessDayTimestamp("10:18");
const mockToday1042 = createCurrentBusinessDayTimestamp("10:42");
const mockToday1152 = createCurrentBusinessDayTimestamp("11:52");
const mockToday1224 = createCurrentBusinessDayTimestamp("12:24");
const mockToday1318 = createCurrentBusinessDayTimestamp("13:18");
const mockToday1605 = createCurrentBusinessDayTimestamp("16:05");

const currentBusinessDate = new Intl.DateTimeFormat("en-CA", {
  timeZone: "America/Mexico_City",
  year: "numeric",
  month: "2-digit",
  day: "2-digit",
}).format(new Date());

export const initialCompetitions: SalesCompetition[] = [
  {
    id: "competition-daily-sales",
    name: "Venta del día",
    type: "AMOUNT",
    active: true,
    dateFrom: currentBusinessDate,
    dateTo: currentBusinessDate,
    branch: "ALL",
    targetAmount: 2_500,
    productId: null,
    packageProductIds: [],
    createdAtIso: new Date().toISOString(),
  },
];

export const products: Product[] = [
  {
    id: "prod-serum-renewal",
    name: "Renewal Peptide Serum",
    sku: "KSR-SER-001",
    family: "Keysar Skin",
    category: "Sérums",
    group: "Cuidado facial",
    kind: "PRODUCT",
    image: "/products/renewal-serum.png",
    description:
      "Sérum de textura sedosa que acompaña la renovación visible de la piel y deja una apariencia tersa, luminosa y confortable.",
    benefits: [
      "Favorece una apariencia más firme",
      "Aporta luminosidad y suavidad",
      "Textura ligera de rápida absorción",
    ],
    showInDigitalCatalog: true,
    minPrice: 690,
    maxPrice: 890,
    includesVat: true,
    costUsd: 18,
    costMxn: 330,
    supplierId: "supplier-keysar-labs",
    supplierName: "Keysar Labs International",
    presentation: "Caja con 6 piezas",
    unitsPerPackage: 6,
    testerOrderEnabled: true,
    stock: 18,
    stockMin: 5,
    stockMax: 30,
    branches: ["Polanco", "Satélite", "Roma Norte"],
    active: true,
  },
  {
    id: "prod-hydra-cloud",
    name: "Hydra Cloud Cream",
    sku: "KSR-HID-014",
    family: "Keysar Skin",
    category: "Hidratación",
    group: "Cuidado facial",
    kind: "PRODUCT",
    image: "/products/hydra-cloud-cream.png",
    description:
      "Crema envolvente de sensación nube que ayuda a conservar la hidratación y aporta confort sin una sensación pesada.",
    benefits: [
      "Hidratación prolongada",
      "Acabado suave y aterciopelado",
      "Ideal para el ritual diario",
    ],
    showInDigitalCatalog: true,
    minPrice: 580,
    maxPrice: 760,
    includesVat: true,
    costUsd: 15,
    costMxn: 280,
    supplierId: "supplier-keysar-labs",
    supplierName: "Keysar Labs International",
    presentation: "Caja con 6 piezas",
    unitsPerPackage: 6,
    testerOrderEnabled: false,
    stock: 12,
    stockMin: 4,
    stockMax: 24,
    branches: ["Polanco", "Satélite"],
    active: true,
  },
  {
    id: "prod-vitamin-c",
    name: "Vitamin C Glow",
    sku: "KSR-SER-008",
    family: "Keysar Skin",
    category: "Sérums",
    group: "Cuidado facial",
    kind: "PRODUCT",
    image: "/products/vitamin-c-glow.png",
    description:
      "Concentrado antioxidante que ilumina la apariencia del rostro y complementa la rutina con un acabado fresco y uniforme.",
    benefits: [
      "Ayuda a recuperar la luminosidad",
      "Contribuye a una apariencia uniforme",
      "Sensación fresca y refinada",
    ],
    showInDigitalCatalog: true,
    minPrice: 620,
    maxPrice: 820,
    includesVat: true,
    costUsd: 16,
    costMxn: 295,
    supplierId: "supplier-keysar-labs",
    supplierName: "Keysar Labs International",
    presentation: "Caja con 12 piezas",
    unitsPerPackage: 12,
    testerOrderEnabled: true,
    stock: 9,
    stockMin: 3,
    stockMax: 20,
    branches: ["Polanco", "Roma Norte"],
    active: true,
  },
  {
    id: "prod-spf-50",
    name: "Mineral Shield SPF 50",
    sku: "KSR-SOL-020",
    family: "Protección Solar",
    category: "Protección",
    group: "Cuidado facial",
    kind: "PRODUCT",
    image: "/products/mineral-spf-50.png",
    description:
      "Protección mineral diaria de textura elegante que acompaña la piel frente a la exposición solar con un acabado cómodo.",
    benefits: [
      "Protección de amplio espectro SPF 50",
      "Textura de uso cotidiano",
      "Complemento esencial del cuidado facial",
    ],
    showInDigitalCatalog: true,
    minPrice: 420,
    maxPrice: 590,
    includesVat: true,
    costUsd: 11,
    costMxn: 205,
    supplierId: "supplier-solaris",
    supplierName: "Solaris Dermal México",
    presentation: "Caja con 12 piezas",
    unitsPerPackage: 12,
    testerOrderEnabled: false,
    stock: 24,
    stockMin: 8,
    stockMax: 40,
    branches: ["Polanco", "Satélite", "Roma Norte"],
    active: true,
  },
  {
    id: "service-brow-sculpt",
    name: "Brow Sculpt",
    sku: "SRV-BRW-003",
    family: "Servicios",
    category: "Cejas",
    group: "Servicios de belleza",
    kind: "SERVICE",
    image: "/products/brow-sculpt.png",
    description:
      "Diseño de ceja personalizado que armoniza las facciones y crea un acabado pulido respetando la expresión natural.",
    benefits: [
      "Diseño adaptado al rostro",
      "Definición de apariencia natural",
      "Atención profesional personalizada",
    ],
    showInDigitalCatalog: true,
    minPrice: 350,
    maxPrice: 520,
    includesVat: true,
    costUsd: 0,
    costMxn: 0,
    stock: null,
    stockMin: null,
    stockMax: null,
    branches: ["Polanco", "Satélite"],
    active: true,
  },
  {
    id: "service-signature-facial",
    name: "Signature Facial",
    sku: "SRV-FAC-001",
    family: "Servicios",
    category: "Faciales",
    group: "Servicios de belleza",
    kind: "SERVICE",
    image: "/products/signature-facial.png",
    description:
      "Ritual facial insignia que combina preparación, cuidado y relajación para devolver al rostro una apariencia descansada y radiante.",
    benefits: [
      "Protocolo ajustado a la piel",
      "Experiencia de relajación profunda",
      "Apariencia luminosa y revitalizada",
    ],
    showInDigitalCatalog: true,
    minPrice: 780,
    maxPrice: 1100,
    includesVat: true,
    costUsd: 0,
    costMxn: 0,
    stock: null,
    stockMin: null,
    stockMax: null,
    branches: ["Polanco", "Roma Norte"],
    active: true,
  },
];

const currentBusinessMonth = currentBusinessDate.slice(0, 7);
const currentBusinessMonthEnd = new Date(
  Date.UTC(
    Number(currentBusinessDate.slice(0, 4)),
    Number(currentBusinessDate.slice(5, 7)),
    0,
  ),
)
  .toISOString()
  .slice(0, 10);

export const initialDeals: RetailDeal[] = [
  {
    id: "deal-glow-ritual",
    name: "Glow Ritual",
    sku: "DEAL-GLW-001",
    description: "Renovación facial y definición de ceja en una sola experiencia.",
    price: 990,
    lines: [
      { productId: "prod-serum-renewal", quantity: 1 },
      { productId: "service-brow-sculpt", quantity: 1 },
    ],
    branches: ["Polanco", "Satélite", "Roma Norte"],
    startDate: `${currentBusinessMonth}-01`,
    endDate: currentBusinessMonthEnd,
    status: "PUBLISHED",
    createdAtIso: new Date().toISOString(),
    publishedAtIso: new Date().toISOString(),
    authorizedBy: "Master Keysar",
  },
  {
    id: "deal-hydra-protection",
    name: "Hydra Protection",
    sku: "DEAL-HYD-002",
    description: "Hidratación y protección diaria para una rutina completa.",
    price: 1_090,
    lines: [
      { productId: "prod-hydra-cloud", quantity: 1 },
      { productId: "prod-spf-50", quantity: 1 },
    ],
    branches: ["Polanco"],
    startDate: `${currentBusinessMonth}-01`,
    endDate: currentBusinessMonthEnd,
    status: "DRAFT",
    createdAtIso: new Date().toISOString(),
    publishedAtIso: null,
    authorizedBy: null,
  },
];

export const sellers: Seller[] = [
  {
    id: "seller-ana",
    name: "Ana Torres",
    alias: "ana",
    initials: "AT",
    active: true,
    accessCode: "1101",
    masterAccessCode: null,
    canViewCosts: true,
    roleId: "role-manager",
  },
  {
    id: "seller-sofia",
    name: "Sofía Méndez",
    alias: "sofia",
    initials: "SM",
    active: true,
    accessCode: "2202",
    masterAccessCode: null,
    canViewCosts: false,
    roleId: "role-seller",
  },
  {
    id: "seller-daniela",
    name: "Daniela Ruiz",
    alias: "daniela",
    initials: "DR",
    active: true,
    accessCode: "3303",
    masterAccessCode: null,
    canViewCosts: false,
    roleId: "role-seller",
  },
  {
    id: "seller-paola",
    name: "Paola Castro",
    alias: "paola",
    initials: "PC",
    active: false,
    accessCode: "4404",
    masterAccessCode: null,
    canViewCosts: false,
    roleId: "role-seller",
  },
];

export const initialExpenseTypes: ExpenseType[] = [
  { id: "expense-transport", name: "Transporte y mensajería", active: true },
  { id: "expense-supplies", name: "Insumos de sucursal", active: true },
  { id: "expense-maintenance", name: "Mantenimiento", active: true },
  { id: "expense-courtesy", name: "Atención a clientas", active: true },
  { id: "expense-other", name: "Otros gastos autorizados", active: true },
];

export const initialCashExpenses: CashExpense[] = [
  {
    id: "cash-expense-today-1",
    folio: "GTO-DEMO-0001",
    createdAt: mockToday1018.createdAt,
    createdAtIso: mockToday1018.createdAtIso,
    expenseDate: currentBusinessDate,
    typeId: "expense-transport",
    typeName: "Transporte y mensajería",
    amount: 185,
    branch: "Polanco",
    sellerId: "seller-ana",
    sellerName: "Ana Torres",
    concept: "Mensajería de producto a clienta",
    comment: "Entrega prioritaria autorizada por gerencia.",
    authorizedBy: "Ana Torres · código empleado",
    status: "ACTIVE",
    updatedAtIso: null,
  },
  {
    id: "cash-expense-today-2",
    folio: "GTO-DEMO-0002",
    createdAt: mockToday1224.createdAt,
    createdAtIso: mockToday1224.createdAtIso,
    expenseDate: currentBusinessDate,
    typeId: "expense-supplies",
    typeName: "Insumos de sucursal",
    amount: 320,
    branch: "Satélite",
    sellerId: "seller-sofia",
    sellerName: "Sofía Méndez",
    concept: "Material de empaque",
    comment: "Bolsas y papel para ticket de la operación del día.",
    authorizedBy: "Sofía Méndez · código empleado",
    status: "ACTIVE",
    updatedAtIso: null,
  },
  {
    id: "cash-expense-history-1",
    folio: "GTO-DEMO-0003",
    createdAt: "22 ago 2026 · 06:05 p.m.",
    createdAtIso: "2026-08-22T18:05:00-06:00",
    expenseDate: "2026-08-22",
    typeId: "expense-maintenance",
    typeName: "Mantenimiento",
    amount: 740,
    branch: "Roma Norte",
    sellerId: "seller-daniela",
    sellerName: "Daniela Ruiz",
    concept: "Ajuste de iluminación",
    comment: "Cambio de luminaria en cabina facial.",
    authorizedBy: "Master Keysar",
    status: "ACTIVE",
    updatedAtIso: null,
  },
];

export const initialEmployeeRoles: EmployeeRole[] = [
  {
    id: "role-master",
    name: "Master",
    description: "Control total del sistema, usuarios, sucursales y configuración.",
    active: true,
    system: true,
    moduleAccess: [
      "dashboard",
      "sale",
      "seller-sales",
      "receipts",
      "customers",
      "appointments",
      "inventory",
      "warehouse",
      "suppliers",
      "inventory-movements",
      "deals",
      "catalog",
      "settings",
      "x-report",
      "reports",
      "cash-manager",
      "clock-in",
      "close-day",
      "employees",
      "competition",
      "websites",
      "data-update",
      "my-account",
    ],
    moduleEditAccess: [
      "dashboard", "sale", "seller-sales", "receipts", "customers",
      "appointments", "inventory", "warehouse", "suppliers",
      "inventory-movements", "deals", "catalog", "settings", "x-report",
      "reports", "cash-manager", "clock-in", "close-day", "employees",
      "competition", "websites", "data-update", "my-account",
    ],
    configurationAccess: [
      "TICKET",
      "INVENTORY_CATALOG",
      "INVENTORY_AUDIT",
      "INVENTORY_MOVEMENTS",
      "WAREHOUSE_MOVEMENTS",
      "PAYMENT_METHODS",
      "CUSTOMER_FIELDS",
      "DEALS",
      "COMPETITIONS",
      "REPORTS_COSTS",
      "BRANCHES",
      "USERS_ROLES",
    ],
  },
  {
    id: "role-manager",
    name: "Gerente de sucursal",
    description: "Supervisa venta, clientes, inventario, cierres y reportes de su operación.",
    active: true,
    system: false,
    moduleAccess: [
      "dashboard",
      "sale",
      "seller-sales",
      "receipts",
      "customers",
      "appointments",
      "inventory",
      "warehouse",
      "inventory-movements",
      "catalog",
      "settings",
      "x-report",
      "reports",
      "cash-manager",
      "clock-in",
      "close-day",
      "competition",
      "data-update",
    ],
    moduleEditAccess: [
      "sale", "seller-sales", "receipts", "customers", "appointments",
      "inventory", "warehouse", "inventory-movements", "catalog", "settings",
      "cash-manager", "clock-in", "close-day", "data-update",
    ],
    configurationAccess: [
      "TICKET",
      "INVENTORY_CATALOG",
      "INVENTORY_MOVEMENTS",
      "CUSTOMER_FIELDS",
    ],
  },
  {
    id: "role-seller",
    name: "Vendedor retail",
    description: "Opera ventas, consulta su cartera, registra citas y revisa sus resultados.",
    active: true,
    system: false,
    moduleAccess: [
      "sale",
      "seller-sales",
      "customers",
      "appointments",
      "clock-in",
      "competition",
    ],
    moduleEditAccess: [
      "sale", "seller-sales", "customers", "appointments", "clock-in",
    ],
    configurationAccess: [],
  },
  {
    id: "role-inventory",
    name: "Encargado de inventario",
    description: "Administra existencias, movimientos, pedidos y catálogo operativo.",
    active: true,
    system: false,
    moduleAccess: [
      "dashboard",
      "inventory",
      "warehouse",
      "suppliers",
      "inventory-movements",
      "catalog",
      "data-update",
      "clock-in",
    ],
    moduleEditAccess: [
      "inventory", "warehouse", "suppliers", "inventory-movements",
      "catalog", "data-update", "clock-in",
    ],
    configurationAccess: ["INVENTORY_CATALOG", "INVENTORY_AUDIT", "INVENTORY_MOVEMENTS", "WAREHOUSE_MOVEMENTS"],
  },
];

export const masterUser: MasterUser = {
  id: "user-master",
  name: "Master Keysar",
  initials: "MK",
  active: true,
  accessCode: "2468",
  role: "MASTER",
};

export const initialPaymentMethods: PaymentMethodOption[] = [
  { id: "CASH", label: "Efectivo", active: true },
  { id: "CARD", label: "Tarjeta", active: true },
  { id: "TRANSFER", label: "Transferencia", active: true },
];

export const initialReceiptSettings: ReceiptSettings = {
  logoUrl: "/logo.svg",
  logoWidth: 64,
  companyName: "KEYSAR COSMETICS",
  branchName: "Sucursal Polanco",
  address: "Av. Presidente Masaryk 123, Polanco, CDMX",
  footerMessage: "Gracias por confiar en tu belleza.",
  policies:
    "Cambios dentro de 7 días con ticket y producto cerrado. Servicios no reembolsables.",
  showClientName: true,
  showClientPhone: false,
  showSellerName: true,
  showVatBreakdown: false,
  showSpareCoverageMessage: true,
};

export const initialInventoryMovementReasons: InventoryMovementReason[] = [
  { id: "reason-tester", name: "Tester", active: true },
  { id: "reason-damage", name: "Damage", active: true },
  { id: "reason-lost", name: "Lost", active: true },
  { id: "reason-gift", name: "Gift", active: true },
];

export const initialInventoryMovements: InventoryMovement[] = [
  {
    id: "movement-demo-sale",
    folio: "MOV-AGO-0001",
    ...mockToday1318,
    productId: "prod-serum-renewal",
    productName: "Renewal Peptide Serum",
    direction: "REMOVE",
    reason: "Venta",
    quantity: 2,
    previousStock: 20,
    newStock: 18,
    sourceBranch: "Polanco",
    destinationBranch: null,
    destinationPreviousStock: null,
    destinationNewStock: null,
    comment: "Salida consolidada de tickets del día",
    category: "SALE",
    unitCostUsd: 18,
    unitCostMxn: 330,
    totalCostUsd: 36,
    totalCostMxn: 660,
  },
  {
    id: "movement-demo-writeoff",
    folio: "MOV-AGO-0002",
    ...mockToday1042,
    productId: "prod-hydra-cloud",
    productName: "Hydra Cloud Cream",
    direction: "REMOVE",
    reason: "Damage",
    quantity: 1,
    previousStock: 9,
    newStock: 8,
    sourceBranch: "Satélite",
    destinationBranch: null,
    destinationPreviousStock: null,
    destinationNewStock: null,
    comment: "Empaque dañado",
    category: "WRITE_OFF",
    unitCostUsd: 14.5,
    unitCostMxn: 270,
    totalCostUsd: 14.5,
    totalCostMxn: 270,
  },
  {
    id: "movement-demo-tester",
    folio: "MOV-AGO-0003",
    ...mockToday1605,
    productId: "prod-spf-50",
    productName: "Mineral Shield SPF 50",
    direction: "REMOVE",
    reason: "Tester",
    quantity: 1,
    previousStock: 7,
    newStock: 6,
    sourceBranch: "Roma Norte",
    destinationBranch: null,
    destinationPreviousStock: null,
    destinationNewStock: null,
    comment: "Demostración en piso de venta",
    category: "DEMO",
    unitCostUsd: 11,
    unitCostMxn: 205,
    totalCostUsd: 11,
    totalCostMxn: 205,
  },
  {
    id: "movement-demo-transfer",
    folio: "MOV-AGO-0004",
    ...mockToday0915,
    productId: "prod-serum-renewal",
    productName: "Renewal Peptide Serum",
    direction: "TRANSFER",
    reason: "Transferencia Polanco → Satélite",
    quantity: 1,
    previousStock: 19,
    newStock: 18,
    sourceBranch: "Polanco",
    destinationBranch: "Satélite",
    destinationPreviousStock: 10,
    destinationNewStock: 11,
    comment: "Reposición entre sucursales",
    category: "TRANSFER",
    unitCostUsd: 18,
    unitCostMxn: 330,
    totalCostUsd: 18,
    totalCostMxn: 330,
  },
];

export const initialClientSources: ClientSourceOption[] = [
  { id: "APPROACH", label: "Abordaje", active: true, locksCompany: false },
  { id: "LEAD", label: "Lead", active: true, locksCompany: true },
  {
    id: "REFERRAL",
    label: "Recomendado",
    active: true,
    locksCompany: false,
  },
  {
    id: "SOCIAL",
    label: "Redes sociales",
    active: true,
    locksCompany: true,
  },
];

export const initialClients: Client[] = [
  {
    id: "client-1",
    registrationFolio: "CLI-2026-0001",
    registeredAtIso: "2026-02-14T10:30:00-06:00",
    firstName: "Valeria",
    lastName: "Campos",
    birthday: "1992-08-23",
    gender: "Mujer",
    phone: "55 1087 2254",
    whatsapp: "55 1087 2254",
    source: "APPROACH",
    sourceLabel: "Abordaje",
    companyName: "",
    companyLocked: false,
    ownerId: "seller-ana",
    saleSellerIds: ["seller-ana"],
  },
  {
    id: "client-2",
    registrationFolio: "CLI-2026-0002",
    registeredAtIso: "2026-03-02T12:15:00-06:00",
    firstName: "Mariana",
    lastName: "López",
    birthday: "1988-10-03",
    gender: "Mujer",
    phone: "55 6712 9041",
    whatsapp: "55 6712 9041",
    source: "LEAD",
    sourceLabel: "Lead",
    companyName: "Keysar Cosmetics",
    companyLocked: true,
    ownerId: "seller-sofia",
    saleSellerIds: ["seller-sofia", "seller-daniela"],
  },
  {
    id: "client-3",
    registrationFolio: "CLI-2026-0003",
    registeredAtIso: "2026-04-21T17:40:00-06:00",
    firstName: "Renata",
    lastName: "Silva",
    birthday: "1996-01-27",
    gender: "Mujer",
    phone: "55 9920 4418",
    whatsapp: "55 9920 4418",
    source: "REFERRAL",
    sourceLabel: "Recomendado",
    companyName: "",
    companyLocked: false,
    ownerId: null,
    saleSellerIds: ["seller-daniela"],
  },
];

export const initialAppointments: Appointment[] = [
  {
    id: "appointment-demo-1",
    kind: "COURTESY",
    service: "Facial de cortesía",
    date: "2026-08-24",
    branch: "Polanco",
    time: "11:30",
    clientId: "client-1",
    clientName: "Valeria Campos",
    clientPhone: "55 1087 2254",
    ticketId: "KSR-1048",
    sellerIds: ["seller-ana"],
    recordedAt: "22 ago 2026 · 12:24",
    recordedAtIso: "2026-08-22T12:24:00-06:00",
    status: "SCHEDULED",
  },
  {
    id: "appointment-demo-2",
    kind: "NEXT_SESSION",
    service: "Facial de seguimiento",
    date: "2026-08-27",
    branch: "Satélite",
    time: "17:00",
    clientId: "client-2",
    clientName: "Mariana López",
    clientPhone: "55 6712 9041",
    ticketId: "KSR-1047",
    sellerIds: ["seller-sofia", "seller-daniela"],
    recordedAt: "22 ago 2026 · 11:52",
    recordedAtIso: "2026-08-22T11:52:00-06:00",
    status: "SCHEDULED",
  },
  {
    id: "appointment-demo-3",
    kind: "NO_APPOINTMENT",
    service: "Sin próxima cita facial",
    date: "2026-08-22",
    branch: "Polanco",
    time: "Sin horario",
    clientId: "client-3",
    clientName: "Renata Silva",
    clientPhone: "55 9920 4418",
    ticketId: "KSR-1045",
    sellerIds: ["seller-daniela"],
    recordedAt: "21 ago 2026 · 18:40",
    recordedAtIso: "2026-08-21T18:40:00-06:00",
    status: "PENDING",
  },
];

export const posBranches = ["Polanco", "Satélite", "Roma Norte"];

export const initialBranchInventory: BranchInventory = posBranches.reduce(
  (branches, branch, branchIndex) => {
    branches[branch] = Object.fromEntries(
      products
        .filter((product) => product.kind === "PRODUCT")
        .map((product) => [
          product.id,
          product.branches.includes(branch)
            ? branchIndex === 0
              ? (product.stock ?? 0)
              : Math.floor(
                  (product.stock ?? 0) * (branchIndex === 1 ? 0.65 : 0.45),
                )
            : 0,
        ]),
    );
    return branches;
  },
  {} as BranchInventory,
);

export const initialLayaways: LayawayRecord[] = [
  {
    id: "layaway-demo-valeria",
    originalTicketId: "KSR-0901",
    createdAt: "10 mar 2026 · 16:20",
    createdAtIso: "2026-03-10T16:20:00-06:00",
    clientId: "client-1",
    clientName: "Valeria Campos",
    clientPhone: "55 1087 2254",
    branch: "Polanco",
    sellerIds: ["seller-ana"],
    total: 1780,
    amountPaid: 880,
    balanceDue: 900,
    items: [
      {
        cartItemId: "demo-renewal",
        productId: "prod-serum-renewal",
        productName: "Renewal Peptide Serum",
        kind: "PRODUCT",
        quantity: 2,
        deliveredQuantity: 1,
      },
    ],
    payments: [
      {
        id: "layaway-demo-payment",
        folio: "APT-DEMO-001",
        createdAt: "10 mar 2026 · 16:20",
        createdAtIso: "2026-03-10T16:20:00-06:00",
        amount: 880,
        methodId: "CARD",
      },
    ],
    status: "ACTIVE",
  },
];

export const initialTickets: Ticket[] = [
  {
    id: "KSR-1048",
    ...mockToday1224,
    clientName: "Valeria Campos",
    clientPhone: "55 1087 2254",
    branchName: "Polanco",
    sellerSummary: "Ana Torres",
    items: 2,
    discountAmount: 0,
    subtotal: 1430,
    total: 1430,
    netTotal: 1232.76,
    vatAmount: 197.24,
    deviation: 160,
    paymentMethod: "CASH",
    payments: [{ id: "pay-1048-1", methodId: "CASH", amount: 1430 }],
    amountPaid: 1430,
    balanceDue: 0,
    paymentStatus: "PAID",
    products: [
      {
        productId: "prod-serum-renewal",
        name: "Renewal Peptide Serum",
        quantity: 1,
        total: 890,
      },
      {
        productId: "service-brow-sculpt",
        name: "Brow Sculpt",
        quantity: 1,
        total: 540,
      },
    ],
    sellerSales: [
      { sellerId: "seller-ana", sellerName: "Ana Torres", amount: 1430 },
    ],
    status: "COMPLETED",
  },
  {
    id: "KSR-1047",
    ...mockToday1152,
    clientName: "Mariana López",
    clientPhone: "55 6712 9041",
    branchName: "Satélite",
    sellerSummary: "Sofía Méndez / Daniela Ruiz",
    items: 3,
    discountAmount: 120,
    subtotal: 1880,
    total: 1760,
    netTotal: 1517.24,
    vatAmount: 242.76,
    deviation: 230,
    paymentMethod: "CARD",
    payments: [{ id: "pay-1047-1", methodId: "CARD", amount: 1760 }],
    amountPaid: 1760,
    balanceDue: 0,
    paymentStatus: "PAID",
    products: [
      {
        productId: "prod-hydra-cloud",
        name: "Hydra Cloud Cream",
        quantity: 2,
        total: 1220,
      },
      {
        productId: "service-brow-sculpt",
        name: "Brow Sculpt",
        quantity: 1,
        total: 540,
      },
    ],
    sellerSales: [
      {
        sellerId: "seller-sofia",
        sellerName: "Sofía Méndez",
        amount: 880,
      },
      {
        sellerId: "seller-daniela",
        sellerName: "Daniela Ruiz",
        amount: 880,
      },
    ],
    status: "COMPLETED",
  },
  {
    id: "KSR-1046",
    ...mockToday1018,
    clientName: "Venta mostrador",
    clientPhone: "",
    branchName: "Roma Norte",
    sellerSummary: "Ana Torres",
    items: 1,
    discountAmount: 0,
    subtotal: 540,
    total: 540,
    netTotal: 465.52,
    vatAmount: 74.48,
    deviation: -40,
    paymentMethod: "TRANSFER",
    payments: [{ id: "pay-1046-1", methodId: "TRANSFER", amount: 300 }],
    amountPaid: 300,
    balanceDue: 240,
    paymentStatus: "LAYAWAY",
    products: [
      {
        productId: "service-brow-sculpt",
        name: "Brow Sculpt",
        quantity: 1,
        total: 540,
      },
    ],
    sellerSales: [
      { sellerId: "seller-ana", sellerName: "Ana Torres", amount: 540 },
    ],
    status: "COMPLETED",
  },
  {
    id: "KSR-1045",
    createdAt: "21 ago 2026 · 18:40",
    createdAtIso: "2026-08-21T18:40:00-06:00",
    clientName: "Renata Silva",
    clientPhone: "55 9920 4418",
    branchName: "Polanco",
    sellerSummary: "Daniela Ruiz",
    items: 2,
    discountAmount: 0,
    subtotal: 1090,
    total: 1090,
    netTotal: 939.66,
    vatAmount: 150.34,
    deviation: 90,
    paymentMethod: "CASH",
    payments: [],
    amountPaid: 0,
    balanceDue: 1090,
    paymentStatus: "PENDING",
    products: [
      {
        productId: "prod-spf-50",
        name: "Mineral Shield SPF 50",
        quantity: 1,
        total: 590,
      },
      {
        productId: "service-brow-sculpt",
        name: "Brow Sculpt",
        quantity: 1,
        total: 500,
      },
    ],
    sellerSales: [
      {
        sellerId: "seller-daniela",
        sellerName: "Daniela Ruiz",
        amount: 1090,
      },
    ],
    status: "COMPLETED",
  },
];

export const initialRequiredClientFields: RequiredClientFields = {
  firstName: true,
  lastName: true,
  birthday: false,
  gender: false,
  phone: true,
  whatsapp: false,
  source: true,
  companyName: false,
};

export const initialBillingProfile: BillingProfile = {
  personalName: "Emma Keysar",
  companyName: "Keysar Cosmetics",
  notificationEmails: ["administracion@keysarcosmetics.mx"],
};

export const initialBillingCards: BillingCard[] = [
  {
    id: "card-demo-visa",
    holderName: "Emma Keysar",
    brand: "VISA",
    last4: "4242",
    expiryMonth: "12",
    expiryYear: "2029",
    authorizationCodeConfigured: true,
    isDefault: true,
  },
];

export const initialBillingLocations: BillingLocation[] = [
  {
    id: "billing-polanco",
    name: "Polanco",
    costUsd: 79,
    status: "ACTIVE",
    billingStartDate: "2026-01-28",
    nextBillingDate: "2026-08-28",
    paymentCardId: "card-demo-visa",
  },
  {
    id: "billing-satelite",
    name: "Satélite",
    costUsd: 69,
    status: "PENDING",
    billingStartDate: "",
    nextBillingDate: "",
    paymentCardId: null,
  },
  {
    id: "billing-roma",
    name: "Roma Norte",
    costUsd: 69,
    status: "ACTIVE",
    billingStartDate: "2026-02-15",
    nextBillingDate: "2026-09-15",
    paymentCardId: "card-demo-visa",
  },
];

export const initialBillingHistory: BillingHistoryEntry[] = [
  {
    id: "billing-history-aug-polanco",
    invoiceNumber: "INV-2026-0801",
    locationId: "billing-polanco",
    locationName: "Polanco",
    period: "Agosto 2026",
    billedAt: "2026-08-01",
    paidAt: "2026-08-01",
    totalUsd: 79,
    status: "PAID",
    cardLast4: "4242",
  },
  {
    id: "billing-history-aug-roma",
    invoiceNumber: "INV-2026-0802",
    locationId: "billing-roma",
    locationName: "Roma Norte",
    period: "Agosto 2026",
    billedAt: "2026-08-15",
    paidAt: "2026-08-15",
    totalUsd: 69,
    status: "PAID",
    cardLast4: "4242",
  },
  {
    id: "billing-history-jul-polanco",
    invoiceNumber: "INV-2026-0701",
    locationId: "billing-polanco",
    locationName: "Polanco",
    period: "Julio 2026",
    billedAt: "2026-07-01",
    paidAt: "2026-07-02",
    totalUsd: 79,
    status: "PAID",
    cardLast4: "4242",
  },
];

export const administratorCode = masterUser.accessCode;

export const encodeMinimumPrice = (value: number) =>
  Math.round(value).toString();

export const getSellerSkuBase = (product: Product) =>
  product.sku.replace(/-[^-]+$/, "");

export const getSellerSku = (product: Product) =>
  `${getSellerSkuBase(product)}-${encodeMinimumPrice(product.minPrice)}`;

export const formatCurrency = (value: number) =>
  new Intl.NumberFormat("es-MX", {
    style: "currency",
    currency: "MXN",
    minimumFractionDigits: 2,
  }).format(value);
