import {
  normalizeClientPhone,
  normalizeClientText,
  type SchedulerClient,
} from './scheduler-client-presentation'

export {
  normalizeClientPhone,
  normalizeClientText,
  findSchedulerClients,
  type SchedulerClient,
  type SchedulerClientHistoryEntry,
} from './scheduler-client-presentation'

export const initialSchedulerClients: SchedulerClient[] = [
  {
    id: 'client-patricia-delgado',
    fullName: 'Patricia Delgado',
    aliases: [],
    phone: '+52 55 5100 0280',
    normalizedPhone: '525551000280',
    email: 'patricia@example.com',
    alternateEmails: [],
    lastName: 'Delgado',
    gender: 'female',
    birthDate: '1992-09-03',
    createdAt: '2025-10-18',
    history: [
      {
        id: 'history-patricia-first-visit',
        branchId: 'galerias-insurgentes',
        date: '2026-05-12',
        displayName: 'Patricia Delgado',
        bookingId: 'history-booking-patricia-layaway',
      },
      {
        id: 'history-patricia-insurgentes',
        branchId: 'galerias-insurgentes',
        date: '2026-06-30',
        displayName: 'Patricia Delgado',
        bookingId: 'booking-1',
      },
    ],
  },
  {
    id: 'client-maria-camila',
    fullName: 'María Camila Celis',
    aliases: ['Maria Camila Celis'],
    phone: '+52 55 3001 9044',
    normalizedPhone: '525530019044',
    email: 'maria.camila@example.com',
    alternateEmails: [],
    lastName: 'Celis',
    gender: 'female',
    birthDate: '1989-09-14',
    createdAt: '2026-01-22',
    history: [
      {
        id: 'history-maria-follow-up',
        branchId: 'mitikah',
        date: '2026-08-18',
        displayName: 'Maria Camila Celis',
      },
      {
        id: 'history-maria-mitikah',
        branchId: 'mitikah',
        date: '2026-06-30',
        displayName: 'Maria Camila Celis',
        bookingId: 'booking-7',
      },
    ],
  },
  {
    id: 'client-yumi-hirasawa',
    fullName: 'Yumi Hirasawa',
    aliases: [],
    phone: '+52 55 7712 3389',
    normalizedPhone: '525577123389',
    email: 'yumi@example.com',
    alternateEmails: [],
    lastName: 'Hirasawa',
    gender: 'female',
    birthDate: '1994-10-02',
    createdAt: '2025-12-08',
    history: [
      {
        id: 'history-yumi-follow-up',
        branchId: 'galerias-insurgentes',
        date: '2026-08-03',
        displayName: 'Yumi Hirasawa',
      },
      {
        id: 'history-yumi-insurgentes',
        branchId: 'galerias-insurgentes',
        date: '2026-06-30',
        displayName: 'Yumi Hirasawa',
        bookingId: 'booking-14',
      },
    ],
  },
  {
    id: 'client-adriana-acosta',
    fullName: 'Adriana Acosta',
    aliases: [],
    phone: '+52 55 7001 4477',
    normalizedPhone: '525570014477',
    email: 'adriana@example.com',
    alternateEmails: [],
    lastName: 'Acosta',
    gender: 'female',
    birthDate: '1991-09-27',
    createdAt: '2026-03-10',
    history: [
      {
        id: 'history-adriana-follow-up',
        branchId: 'masaryk',
        date: '2026-08-21',
        displayName: 'Adriana Acosta',
      },
      {
        id: 'history-adriana-masaryk',
        branchId: 'masaryk',
        date: '2026-06-30',
        displayName: 'Adriana Acosta',
        bookingId: 'booking-8',
      },
    ],
  },
]
