export type InterfaceLocale = "es" | "en" | "fr" | "pt";

export const interfaceLanguages: Array<{ code: InterfaceLocale; short: string; name: string }> = [
  { code: "es", short: "ES", name: "Español" },
  { code: "en", short: "EN", name: "English" },
  { code: "fr", short: "FR", name: "Français" },
  { code: "pt", short: "PT", name: "Português" },
];

export const uiText = {
  es: { menu: "MENÚ ADMINISTRATIVO", newEmployee: "Nuevo empleado", employees: "Todos los empleados", personal: "Personal y horarios", calendar: "Calendario", requests: "Solicitudes", vacations: "Historial de vacaciones", branches: "Sucursales", access: "Usuarios y permisos", settings: "Preferencias", language: "Idioma", appearance: "Apariencia", light: "Claro", dark: "Oscuro", brand: "Logotipo y marca", editBrand: "Editar logotipo y marca", primaryName: "Nombre principal", secondaryName: "Nombre secundario", logo: "Logotipo JPG o PNG", saveBrand: "Guardar identidad", saving: "Guardando…", close: "Cerrar", logout: "Salir", master: "Usuario Maestro", admin: "Acceso administrativo", app: "Instalar aplicación" },
  en: { menu: "ADMIN MENU", newEmployee: "New employee", employees: "All employees", personal: "Staff and schedules", calendar: "Calendar", requests: "Requests", vacations: "Vacation history", branches: "Locations", access: "Users and permissions", settings: "Preferences", language: "Language", appearance: "Appearance", light: "Light", dark: "Dark", brand: "Logo and brand", editBrand: "Edit logo and brand", primaryName: "Primary name", secondaryName: "Secondary name", logo: "JPG or PNG logo", saveBrand: "Save identity", saving: "Saving…", close: "Close", logout: "Sign out", master: "Master User", admin: "Administrative access", app: "Install application" },
  fr: { menu: "MENU ADMINISTRATIF", newEmployee: "Nouvel employé", employees: "Tous les employés", personal: "Personnel et horaires", calendar: "Calendrier", requests: "Demandes", vacations: "Historique des congés", branches: "Succursales", access: "Utilisateurs et autorisations", settings: "Préférences", language: "Langue", appearance: "Apparence", light: "Clair", dark: "Sombre", brand: "Logo et marque", editBrand: "Modifier le logo et la marque", primaryName: "Nom principal", secondaryName: "Nom secondaire", logo: "Logo JPG ou PNG", saveBrand: "Enregistrer l’identité", saving: "Enregistrement…", close: "Fermer", logout: "Quitter", master: "Utilisateur maître", admin: "Accès administratif", app: "Installer l’application" },
  pt: { menu: "MENU ADMINISTRATIVO", newEmployee: "Novo funcionário", employees: "Todos os funcionários", personal: "Equipe e horários", calendar: "Calendário", requests: "Solicitações", vacations: "Histórico de férias", branches: "Filiais", access: "Usuários e permissões", settings: "Preferências", language: "Idioma", appearance: "Aparência", light: "Claro", dark: "Escuro", brand: "Logotipo e marca", editBrand: "Editar logotipo e marca", primaryName: "Nome principal", secondaryName: "Nome secundário", logo: "Logotipo JPG ou PNG", saveBrand: "Salvar identidade", saving: "Salvando…", close: "Fechar", logout: "Sair", master: "Usuário mestre", admin: "Acesso administrativo", app: "Instalar aplicativo" },
} as const;
